spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dbspace/omnichannel-config-repo
          username:
          passphrase:
server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://admin:password@${eureka.instance.ip-address}:8761/eureka/